export const CREATE_STUDENT_REQUEST_START = "CREATE_STUDENT_REQUEST_START";
export const CREATE_STUDENT_REQUEST_SUCCESS = "CREATE_STUDENT_REQUEST_SUCCESS";
export const CREATE_STUDENT_REQUEST_FAILURE = "CREATE_STUDENT_REQUEST_FAILURE";

export const DELETE_STUDENT_REQUEST_START = "DELETE_STUDENT_REQUEST_START";
export const DELETE_STUDENT_REQUEST_SUCCESS = "DELETE_STUDENT_REQUEST_SUCCESS";
export const DELETE_STUDENT_REQUEST_FAILURE = "DELETE_STUDENT_REQUEST_FAILURE";

export const GET_CUSTOMERS_REQUEST_START = "GET_CUSTOMERS_REQUEST_START";
export const GET_CUSTOMERS_REQUEST_SUCCESS = "GET_CUSTOMERS_REQUEST_SUCCESS";
export const GET_CUSTOMERS_REQUEST_FAILURE = "GET_CUSTOMERS_REQUEST_FAILURE";

export const LOGIN_REQUEST_START = "LOGIN_REQUEST_START";
export const LOGIN_REQUEST_SUCCESS = "LOGIN_REQUEST_SUCCESS";
export const LOGIN_REQUEST_FAILURE = "LOGIN_REQUEST_FAILURE";


// Synchrones
export const PARSE_CUSTOMERS = "PARSE_CUSTOMERS";
export const PARSE_USER = "PARSE_USER";